### ISSUE TITLE
Implement steps for Zenodo Sandbox that adds version to existing record

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#117]
This is the extended version of #61.
Ideally, we'll get this ready in time.

This could need, e.g.

- configurated concept DOI, or
- retrieving concept DOI based on project heuristics from Zenodo (i.e., an API "harvester")

**Comment by zyzzyxdonta** [comment]
This should also include updating an existing record (i.e. only changing the metadata without creating a new version and changing files) as it also needs the configured DOI/url to publication/...

**Comment by zyzzyxdonta** [comment]
Related: #14
