### ISSUE TITLE
Process step creates `autor[*].name` values

### ISSUE THREAD

**Issue by jkelling** [hermes-hmc/workflow#155]
The `cff` harvester harvests author names as `givenName` and `familyName` (stored in `.hermes/harvest/cff.json`). The processed data in `.hermes/process/codemeta.json` contains `givenName`, `familyName` and `name`, where the latter is made up form the other two. Codemeta seems to [specify](https://codemeta.github.io/terms/), that `name` should only be given if the name cannot be split into `givenName` and `familyName`.

**Comment by jkelling** [comment]
This behavior looks very intentional:
https://github.com/hermes-hmc/workflow/blob/05e4e530af77bd38810dd802c5c4f1b8249a8ca5/src/hermes/commands/process/cff.py#L28-L32

Maybe we should discuss, whether we need this and how much we want to follow or ignore codemeta here.

**Comment by led02** [comment]
Well, in fact I also think it's good to remove this for several reasons:

- It was introduced to be able to mach GitLab authors to CFF authors. Hence, it currently has no "use".
- It was the very first processing extension and thus also used for demonstration purposes.
- There is no added information here.

Maybe we can still keep the implementation (as an example) but disable it by default?

**Comment by led02** [comment]
The above described behaviour is implemented in #152 (i.e., the implementation is still available as `cff_add_name` processor but is no longer automatically run).
