### ISSUE TITLE
Design model context API

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#17]
Things to consider:

- How to deal with complex objects/collections?
    - E.g., `authors.author.name` ...

**Comment by led02** [comment]
We have a `ContextPath` object to deal with complex paths. The model can project them to the data in a flexible manner.

**Comment by sdruskat** [comment]
@led02 Can this be considered fixed as part of merging #40? If so, please add the `fixes #...` to the PR description.

**Comment by sdruskat** [comment]
This has been fixed as part of #40.
