### ISSUE TITLE
No automatic initial deposits

### ISSUE THREAD

**Issue by led02** [hermes-hmc/workflow#172]
We discussed again that it is not a good idea to automatically make a new deposition if no "old version" is referenced (e.g., DOI does not resolve, no previous record_id provided, ...).

At least a flag should be provided to "allow" initial deposition.

**Comment by poikilotherm** [comment]
I very much agree. This is certainly a pitfall for people that are not absolutely knowing what they are doing. It would be very bad user experience when people by accident create multiple entities on Zenodo/... that are auto-published. There is no way back from such errors - published is published. Deaccession is a possibility, but looks bad.
