### ISSUE TITLE
Avoid pandas dependency from convert-codemeta

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/workflow#189]
As we are only using the validation part of [`convert-codemeta`](https://github.com/caltechlibrary/convert_codemeta), we can avoid installing `pandas`, `numpy` etc in our future Docker container by removing the dependency.

As the code is under a permissive BSD/MIT license, let's simply include it properly in our codebase.

**Comment by jkelling** [comment]
Does this  close #190 ? It should be linked either way.
