### ISSUE TITLE
How to handle metadata source metadata?

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#19]
When adding metadata to the `HermesContext` using (`context.update()`), one has to provide a source for provenance tracking.
What do we envision this metadata source metadata to actually look like?

Passing a path string to a local file may not be very helpful, but getting better contextual data (e.g., URi for the file in the source code repo) may not work for all cases (e.g., locally running the workflow).

**Comment by led02** [comment]
When the HermesContext is created, it is linked to the extension that it is passed to. This allows us to have the `source` (or any other keyword arugment) be specific to the extension.

We could say, be default we can handle `source` being a Path or URI. But the idea is to provide an additional `entry_point` with another group but the same name that can then be called to actually "access" the original source (in some way... don't know how exactly yet, but I think this is generic enough).

So, for example if you would have an `git` harverster, you'd call `update('author', commit.author, commit_id=commit.id)`. Later, you would call `entry_points(group='hermes.update_source', name='git').load().update('author', 'Monty Python', commit_id=commit_id)`

**Comment by led02** [comment]
Or, to put it more simple: Just add as many additinal keyword arguments to make it possible for your harvester to back-track the origin...

**Comment by sdruskat** [comment]
Okay, sounds good. Does it make sense to build a vocabulary of things that make sense to record? Or should they dynamically be discovered during API access?

**Comment by sdruskat** [comment]
Decided against a vocabulary, but commit IDs may be useful (tracked in #99).
