### ISSUE TITLE
trailing whitespaces breaks pre-commit: trailing-whitespace

### ISSUE THREAD

**Issue by daniel-mohr** [hermes-hmc/workflow#200]
[Set up automatic software publishing](https://docs.software-metadata.pub/en/latest/tutorials/automated-publication-with-ci.html) describes how to integrate your ci-templates.

The provided template for `.gitlab-ci.yml` has [a trailing whitespace](https://github.com/hermes-hmc/workflow/blob/a90b8d38f7aab9cc12fd2ba2c3610994e72e7679/docs/source/tutorials/automated-publication-with-ci.md?plain=1#L179C51-L179C51).

cf. https://github.com/hermes-hmc/ci-templates/issues/5

**Comment by led02** [comment]
Fixed in https://github.com/hermes-hmc/ci-templates/issues/5

**Comment by led02** [comment]
https://github.com/hermes-hmc/ci-templates/issues/5
