### ISSUE TITLE
Tutorial: Gitlab HERMES_PUSH_TOKEN not documented

### ISSUE THREAD

**Issue by daniel-mohr** [hermes-hmc/workflow#201]
[Set up automatic software publishing](https://docs.software-metadata.pub/en/latest/tutorials/automated-publication-with-ci.html) describes how to set up your workflow.

But it is missing to mention that one has to provide the CI variable `HERMES_PUSH_TOKEN`. This token has to have at least the role `Developer` and needs write access to the project to create branches.

**Comment by led02** [comment]
This relates to the GitLab example / template.

**Comment by daniel-mohr** [comment]
Ah, yes. I used your gitlab workflow/example/template.

**Comment by aghr** [comment]
I ran into the same issue and solved it myself after online investigation. Please update your documentation as soon as possible to avoid that more GitLab users run into this issue. Good documentation is vital for your users. Many thanks.
