### ISSUE TITLE
Write data model ADR

### ISSUE THREAD

**Issue by led02** [hermes-hmc/workflow#22]
Even though there is already some rough base model (especially for havesting), we should write an ADR about it and disucss it.

**Comment by sdruskat** [comment]
**question:** Should this ADR only describe the data model, or should it include decisions on how to build the model, and how to project to different target schemas?

**Comment by sdruskat** [comment]
> **question:** Should this ADR only describe the data model, or should it include decisions on how to build the model, and how to project to different target schemas?

Decision: documenting #53 is in scope for fixing this issue.
