### ISSUE TITLE
Implement processing step

### ISSUE THREAD

**Issue by led02** [hermes-hmc/workflow#26]
Well, the title says it all:

- Second stage = processing
- From discussions, we know that there is kind of a pre-processing step required to transform "harverster-specific" metadata into "codemeta"-data
- Then, the "codmeta"data needs to be processed
    - disambiguation
    - merging of different stuff
- We want to be **very** conservative, i.e., better not guess but prompt for an error

**Comment by led02** [comment]
See #40 for updates

**Comment by sdruskat** [comment]
Closed by merging #40.
