### ISSUE TITLE
Add user feedback when no data sources found

### ISSUE THREAD

**Issue by dstansby** [hermes-hmc/workflow#30]
I ran `haggis` in a random directory with no data sources, and the only output was:
```
% haggis 
Metadata harvesting
Metadata processing
```
It would be good to add some user feedback on the command line to say that no data sources were found.

**Comment by led02** [comment]
Will be fixed by #40 (much more extensive logging)

**Comment by sdruskat** [comment]
> Will be fixed by #40 (much more extensive logging)

Hasn't been fixed in #40, so still needs a fix.
