### ISSUE TITLE
Data harvested from git does not produce process output

### ISSUE THREAD

**Issue by ageorgou** [hermes-hmc/workflow#32]
Because the git harvester does not yet produce codemeta-compatible output.

To reproduce:
- Be in a git repository with no `CITATION.cff`
- Run `haggis`
- `.hermes/harvest/git` is populated, but `.hermes/process` is empty

Expected output:
- `.hermes/process` would list the information harvested from the git history

**Comment by sdruskat** [comment]
True, we're still in the process of implementing this.

**Comment by sdruskat** [comment]
> True, we're still in the process of implementing this, see #25 .

#25 is now part of #40.

**Comment by sdruskat** [comment]
#40 has been merged, so closing.
