### ISSUE TITLE
Building docs fails because of missing dependency

### ISSUE THREAD

**Issue by ageorgou** [hermes-hmc/workflow#33]
Following the instructions:
```bash
poetry run sphinx-apidoc -o docs/source/api src
poetry run sphinx-build -M html docs/source docs/build
```
the second command fails with
```
Running Sphinx v4.5.0
loading translations [en]... done

Extension error:
Could not import extension sphinx-favicon (exception: No module named 'sphinx-favicon')
```

**Comment by ageorgou** [comment]
This is because the sphinx dependencies, listed in `docs/requirements.txt` are not included in `pyproject.toml` or `poetry.lock`, so are not installed. Two ways around this are:
- Add them to the files that poetry looks at
- Add an instruction in README.md to install the sphinx dependencies (e.g. `pip install -r requirements.txt`; it would be nice to have a poetry command for consistency, but [there doesn't appear to be one](https://stackoverflow.com/questions/62764148/how-to-import-requirements-txt-from-an-existing-project-using-poetry), and the suggested workaround there would not work on Windows)

**Comment by poikilotherm** [comment]
Sorry we missed updating the README bits about building the docs! Will update!
