### ISSUE TITLE
Give option to create more readable cache files

### ISSUE THREAD

**Issue by ageorgou** [hermes-hmc/workflow#34]
The cache files created in `.hermes` during harvesting and processing are JSON but not very readable because they are all in one line. This makes sense since they are for internal use only, but it may be useful for debugging to make them more readable.

Perhaps allow an option e.g. `haggis harvest --debug` to write these files with line breaks and indentation?

**Comment by sdruskat** [comment]
I like the idea of having `--debug`, although in "production" this will probably just stay as is.

**Comment by poikilotherm** [comment]
IMHO this is a "nice to have" as it should be achievable by using `jq` to make the JSON-LD readable and highlighted.

**Comment by led02** [comment]
Cache files are prettified in #40

**Comment by sdruskat** [comment]
As of now, cache files are written in a human-readable manner, so this is being closed as fixed in #40.
