### ISSUE TITLE
License project

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#4]
We need licenses for

- [ ] Code
- [ ] Docs
- [ ] Others

These should be reflected via the REUSE Specifications.

**Comment by sdruskat** [comment]
Suggestions:

- Code: [Apache-2.0](https://spdx.org/licenses/Apache-2.0), any objections @jkelling?
- Docs (incl. graphics, etc.): CC BY-SA 4.0 Intl., any objections @jkelling?
- Others: CC0-1.0 Intl., any objections, @jkelling?
- Key visual: CC BY-ND, any objections @jkelling?

CLA? @poikilotherm will prepare with legal if ever we need this. Automation possible via https://github.com/marketplace/cla-bot-cla-automation.

**Comment by jkelling** [comment]
>     * Code: [Apache-2.0](https://spdx.org/licenses/Apache-2.0), any objections @jkelling?

I personally prefer copy-left, e.g. GPL, for code, though I know that some people find enforced freedom overly restrictive and some companies, which may be involved in public research projects, too, would not touch GPL. So I am not actively objecting.

The other are good.

**Comment by sdruskat** [comment]
> > ```
> > * Code: [Apache-2.0](https://spdx.org/licenses/Apache-2.0), any objections @jkelling?
> > ```
> 
> I personally prefer copy-left, e.g. GPL, for code, though I know that some people find enforced freedom overly restrictive and some companies, which may be involved in public research projects, too, would not touch GPL. So I am not actively objecting.
> 
> The other are good.

Thanks. I appreciate the sentiment regarding copy-left. In our case, I think, what speaks against adopting GPL or similar is that we decidedly build something that should be integrated in other tools later on, which may pose a practical issue if we had a copy-left license on our code.

I'll prepare a PR applying the agreed-upon licenses with REUSE 3.0.

**Comment by poikilotherm** [comment]
I poked one of our IP lawyers with this and we'll try to get something started...

**Comment by sdruskat** [comment]
> I poked one of our IP lawyers with this and we'll try to get something started...

Excellent. Perhaps useful to track this in an extra issue?
