### ISSUE TITLE
Implement requirements querying for Invenio

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#55]
To prepare for the deposit, we need to query the target pub repos for metadata requirements, and prepare the deposit respectively.

**Comment by knodel** [comment]
Invenio based repositories provide the metadata record schema typically under `/api/schemas/records/record-v1.0.0.json`:
* Rodare: https://rodare.hzdr.de/api/schemas/records/record-v1.0.0.json
* Zenodo: https://zenodo.org/api/schemas/records/record-v1.0.0.json

**Comment by juckel** [comment]
I find the version number in the URL somewhat worrisome. Even though it seems to be always `record-v1.0.0.json` the presence of a version number clearly shows an intention...

**Comment by knodel** [comment]
> I find the version number in the URL somewhat worrisome. Even though it seems to be always `record-v1.0.0.json` the presence of a version number clearly shows an intention...

Absolutely. A versioning at this point was once intended, but for technical reasons never implemented on the level of the file name. The schema changes regularly but the file name is the same for Zenodo since 2016. 

For current Invenio instances, we have to live with this.
