### ISSUE TITLE
Split authors and contributors

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/workflow#65]
- **Requires:** #52 

Authors and contributors of software are different roles and should end up in different CodeMeta fields.

E.g., 
- person1 is in CFF authors AND git contributors: person is author only
- person1 is in CFF authors AND NOT git contributors: person is author only
- person1 is NOT in CFF authors BUT in git contributors: person is contributor only

This must be implemented as processing step.

**Comment by led02** [comment]
Related to #87

**Comment by sdruskat** [comment]
>     * person1 is in CFF authors AND git contributors: person is author only
> 
>     * person1 is in CFF authors AND NOT git contributors: person is author only
> 
>     * person1 is NOT in CFF authors BUT in git contributors: person is contributor only

This isn't semantically correct, as determined in yesterday's discussion.

git knows committers and authors, where

> the author is the person who originally wrote the work, whereas the committer is the person who last applied the work. So, if you send in a patch to a project and one of the core members applies the patch, both of you get credit — you as the author, and the core member as the committer. ([source](https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History))

This does, however, not mean that git authors are automatically software authors, as software authorship a) can only be determined by the project itself, and b) insinuates a certain _substantial contribution to the conception or design [or implementation] of the work_ (which isn't yet clearly defined by the community).

This in turn means that the most correct thing we can say from just the metadata is that both git authors and git contributors are just that, and that authoritative author metadata cannot be determined from git metadata.

I.e., and in contrast to the above:

* person can only be author if they are defined as such in a semantically authoritative source such as CFF or CodeMeta.
* person will always be contributor (see also below) if they are defined as git committer and git author
* person can be either, or, or both contributor and author
